services:
  popcat-urlshort:
    container_name: popcat-urlshort
    image: ghcr.io/herrerde/popcat-urlshort:latest
    restart: always
    environment:
      - DEBUG=False
      - MONGODB_HOST=db
      - MONGODB_USER=popcat
      - MONGODB_PASS=popcat
      - MONGODB_DATABASE=webservice
      - MONGODB_COLLECTION=urlshort
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: mongo:latest
    restart: always
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=popcat
      - MONGO_INITDB_ROOT_PASSWORD=popcat
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
    driver: local
